// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: passenger.sql

package store

import (
	"context"
)

const getPassengers = `-- name: GetPassengers :many
SELECT id, name FROM passenger ORDER BY id
`

func (q *Queries) GetPassengers(ctx context.Context) ([]Passenger, error) {
	rows, err := q.db.Query(ctx, getPassengers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Passenger
	for rows.Next() {
		var i Passenger
		if err := rows.Scan(&i.Identifier, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
